server:
  port: 8080

  boot:
    admin:
      client:
        url: ${SPRING_BOOT_ADMIN_SERVER_URL:http://localhost:8508}

management:
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: dynamic-routing
          uri: lb://product-service
          predicates:
            - Path=/product-service/**
          filters:
            - RewritePath=/product-service/(?<segment>.*), /${segment}
#            - RewritePath=/(?<segment>.*), /product-service/${segment}    # tamtersi


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka



