server:
  port: 8081

  boot:
    admin:
      client:
        url: ${SPRING_BOOT_ADMIN_SERVER_URL:http://localhost:8508}

management:
  endpoints:
    web:
      exposure:
        include: "*"
  tracing:
    enabled: true                     # Tracing sistemi aktif
    sampling:
      probability: 1.0                # Tüm isteklerin (%100) izlenmesi

spring:
  application:
    name: product-service
  zipkin:
    base-url: http://localhost:9411   # Zipkin sunucusunun adresi
    enabled: true                     # Zipkin entegrasyonunu aç
    locator:
      discovery:
        enabled: true                 # Zipkin adresini Eureka'dan al (aktifse base-url yok sayılır)

  datasource:
    url: jdbc:h2:mem:productdb
    driverClassName: org.h2.Driver
    username: sa
    password: password

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8090/realms/myrealm/protocol/openid-connect/certs

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka




